version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vortexpolis-db
    restart: always
    environment:
      POSTGRES_DB: vortexpolis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: vortexpolis-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vortexpolis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_MAIL_USERNAME: aldemar.vivas02@gmail.com
      SPRING_MAIL_PASSWORD: pjtj xeis xgqv hgdi

volumes:
  postgres_data:
